### ISSUE TITLE
cube-ctl can't start a container

### ISSUE THREAD

**Issue by yunguowei** [OverC/meta-overc#135]
We can deploy a system with cube-essential, cube-dom0 and cube-server.
Steps to reproduce this issue:
1. On dom0, tar cube-server's rootfs:
tar  -xattrs --xattrs-include=security.ima -cjf cube-test.tar.bz2 /opt/container/cube-server/rootfs 

2. add this new container(tarball) to the system

cube-ctl add cube-test.tar.bz2

3. start the container cube-test:

root@cube-dom0:/opt/container# cube-ctl start cube-test
container_linux.go:265: starting container process caused "process_linux.go:347: container init caused \"process_linux.go:330: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: \\\"\""
container "cube-test" does not exist

**Comment by yunguowei** [comment]
This error occurs at cube-test's oci.cmd:

${mgr} create --bundle /opt/container/cube-test --console-socket=/var/lib/cube/cube-test/runc-sock cube-test

**Comment by zeddii** [comment]
I'll grab this one, I'm already working on changes in this area.

**Comment by zeddii** [comment]
This works out of the box for me. Granted I didn't tar up an existing container's rootfs (since it was live), but scp'd it onto the box:

    8  scp bruce@<ip>:/tmp/cube-server*tar.bz2 .
    9  c3 add -n cube-test ./cube-server-genericx86-64-20171028020631.rootfs.tar.bz2
    11  c3 start cube-test

root@cube-dom0:~# c3 list   
name         type  status   attributes  addresses
----         ----  ------   ----------  ---------
cube-server  oci   running  netprime    192.168.42.1,128.224.56.232
cube-test    oci   running  --          192.168.42.167
dom0         cube  running  vrf         192.168.42.3

**Comment by yunguowei** [comment]
scp an pre-built tarball works.
But if tar up an existing rootfs still fails.

**Comment by yunguowei** [comment]
There is some problem with creating rootfs's tarball, so this is not an real issue.

Close it.
